name: K6 load test
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: step 1 - checkout
              uses: actions/checkout@v4

            - name: step 2 - run k6 load test
              uses: grafana/setup-k6-action@v1
            - uses: grafana/run-k6-action@v1
              with:
                path: ./aws/testAwsCloud.js
            
            - run: ls & mkdir report & mv index.html report
                
            - name: step 3 - upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: relatório de testes de performance
                path: report
            
            - name: step 4 - publish report
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_branch: gh-pages
                publish_dir: report

